version: "3"

networks:
  metrics:
    external: false

services:
  influxdb:
    image: influxdb:2.0.7
    container_name: influxdb
    restart: unless-stopped
    networks: [metrics]
    ports:
      - "8086:8086"
    volumes:
      - ./data/influxdb:/var/lib/influxdb2
      - ./influxdb/config.yml:/etc/influxdb2/config.yml
    env_file:
    - .env
  
  nodered:
    image: nodered/node-red:1.3.5
    container_name: node-red
    restart: unless-stopped
    ports:
      - "1880:1880"
    networks: [metrics]
    volumes:
      - ./data/node-red:/data

  mosquitto:
    image: eclipse-mosquitto:2.0.11
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    networks: [metrics]
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf      
      - ./data/mosquitto/data:/mosquitto/data
      - ./data/mosquitto/log:/mosquitto/log

  grafana:
    image: grafana/grafana:8.0.4
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks: [metrics]
    volumes:
      - ./data/grafana:/var/lib/grafana

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    networks: [metrics]
    restart: unless-stopped
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    env_file:
      - .env
  
